### ISSUE TITLE
Program crashes when alphabets are taken as input

### ISSUE THREAD

**Issue by Anuth1302** [YuvarajDakhane/SDLC_Team29_Alpha-Challengers#19]
Inside transaction.c, you need to work in putting constraints

**Comment by Amit-Singh-op** [comment]
Dude if our program wasn't working, how did you get to know it was being crashed when you put an input as alphabets

**Comment by Amit-Singh-op** [comment]
Moreover if we had given some constraints, would you be able to know whether it would work or not without compiling it?
